[package]
name = "ernisto/replication"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Wrapper = "ernisto/wrapper@0.4.0"
Signal = "ernisto/signal@0.1.1"