[package]
name = "pichau/dangeroussky2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Replicator = "ernisto/replicator@0.1.4"
Replication = "ernisto/replication@0.1.2"
Wrapper = "ernisto/wrapper@0.4.1"