[package]
name = "ernisto/replicator"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Wrapper = "ernisto/wrapper@0.3.3"
Signal = "ernisto/signal@0.1.1"